### ISSUE TITLE
Some instructions on how to get started after setup, please

### ISSUE THREAD

**Issue by magthe** [glittershark/org-clubhouse#18]
I'm feeling really stupid, but I don't know how to get started.

I have done all the setup and it seems to work, but now what?

Some instructions on how to start using it would be great, e.g. how do I pull down a project into an Org file so I can start working with already existing epics/stories/etc?

**Comment by glittershark** [comment]
Yeah, this has been necessary for a while (you're not stupid, I just haven't written the docs :P). It would help me a lot if you could list the kinds of questions you'd like answered in those docs (the one you already gave is a great start) and I can make sure to cover everything.

**Comment by glittershark** [comment]
I added some additional usage documentation on a few undocumented commands in 6b701daaa5e49b53065556dc441914718f518c18 - let me know if that answers your initial question, or if there's still stuff that's unclear to you. It's 
also possible that something you're trying to do just isn't supported yet (eg, "pull down an entire project's stories at once" may or may not be doable via `org-clubhouse-headlines-from-query`) in which case please feel free to open feature requests - as it is the commands here are basically a patchwork of the things I added to support *my* workflow. That workflow right now is, for the record:

**Comment by magthe** [comment]
I'm guessing you also have some orgmode setup related to todo-states (I see stuff like `LATER`, `ACTIVE` and `PR` in `org-clubhouse-state-alist`). It'd be lovely to have that setup documented too.

**Comment by glittershark** [comment]
sure! I'll add some bits about that to the readme. In the meantime, my config looks like this:

**Comment by glittershark** [comment]
Does fe52639 look good to you?
It's also likely that the default values in the actual code for the `defvar` of `org-clubhouse-state-alist` should be changed to better match up with the default config of both Clubhouse and org-mode - if you've got a more vanilla clubhouse setup than me I'd love a PR to change that to make things less confusing

**Comment by magthe** [comment]
Excellent. Now I think I have enough to really start trying this out. :+1:

**Comment by glittershark** [comment]
yay! I'm gonna close this issue out then, but please don't hesitate to open more. Happy to have other people using this! :smile:
