### ISSUE TITLE
Missing function org-link-make-string

### ISSUE THREAD

**Issue by vlladdrakk** [glittershark/org-clubhouse#27]
I'm trying to test out this package, but I am getting the following error:
`Symbol’s function definition is void: org-link-make-string`
I can't seem to find out where that function is from, any help is appreciated!

I'm on Emacs 26.3 and I installed org-clubhouse via quelpa.

**Comment by glittershark** [comment]
hmm, `org-link-make-string` is [part of org-mode](https://code.orgmode.org/bzg/org-mode/src/master/lisp/ol.el#L947-L966) - what version of org-mode do you have installed?

**Comment by vlladdrakk** [comment]
Ah, that was the issue, thanks! I was on 9.1.9 and once I upgraded to the latest version it works!
